language: go
branches:
  only:
    - raw
env:
  global:
    - SSH_KEY="travis_key"
    - GIT_NAME="johnson"
    - GIT_EMAIL="onward.edkim@gmail.com"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="code"
    - TEMP_DIR=$(sudo mktemp -d /tmp/$REPO_NAME.XXXX)
before_install:
- openssl aes-256-cbc -K $encrypted_38c9a711ded5_key -iv $encrypted_38c9a711ded5_iv
  -in travis_key.enc -out travis_key -d
before_script:
  - go get -u -v github.com/spf13/hugo
script:
  - git submodule init
  - hugo
after_success:
  - chmod a+x ./scripts/deploy.sh
  - ./scripts/deploy.sh
